#!/bin/bash
installdir=~/bin/atlas
datadir=$1

if [ ! -f "$mypidfile" ] ; then
    python3 ${installdir}/main.py ${datadir}/ 2>&1 | tee ${datadir}/atlas-prep.log

    python2 ${installdir}/reduce.py ${datadir}/ 2>&1 | tee ${datadir}/atlas-reduce.log

    python3 ${installdir}/astrometry.py ${datadir}/ 2>&1 | tee ${datadir}/atlas-astro.log
    python3 ${installdir}/prephot.py ${datadir}/ | tee ${datadir}/atlas-prephot.log

    python2 ${installdir}/phot.py ${datadir}/ 2>&1 | tee ${datadir}/atlas-phot.log

    python3 ${installdir}/graph.py ${datadir}/ 2>&1 | tee ${datadir}/atlas-graph.log
fi
